[package]
name = "hole_punch"
version = "0.1.0"
authors = ["Bastian KÃ¶cher <git@kchr.de>"]

[dependencies]
pnet_datalink = "0.20.0"
tokio-core = "0.1.10"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
futures = "0.1.17"
error-chain = "0.11.0"
tokio-io = "0.1"
tokio-timer = { "git" = "https://github.com/bkchr/tokio-timer.git", "branch" = "interval_range" }
tokio-serde-json = { git = "https://github.com/bkchr/tokio-serde-json.git", branch = "do_not_require_io_error" }
itertools = "0.7.1"
hyper = "0.11"
state_machine_future = { git = "https://github.com/bkchr/state_machine_future.git", "branch" = "complex_type_parsing" }
bincode = "0.8"
h2 = { git = "https://github.com/carllerche/h2.git" }
http = "0.1"
bytes = "0.4"
env_logger = "0.4.3"
log = "0.4.1"
