[package]
name = "hole_punch"
version = "0.1.0"
authors = ["Bastian KÃ¶cher <git@kchr.de>"]

[dependencies]
pnet_datalink = "0.20.0"
tokio-core = "0.1.10"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
futures = "0.1.17"
tokio-io = "0.1"
tokio-timer = { "git" = "https://github.com/bkchr/tokio-timer.git", "branch" = "interval_range" }
tokio-serde-json = { git = "https://github.com/bkchr/tokio-serde-json.git", branch = "do_not_require_io_error" }
itertools = "0.7"
state_machine_future = "^0.1.6"
bincode = "0.8"
bytes = "0.4"
env_logger = "0.4.3"
log = "0.4"
picoquic = { path = "../picoquic"  }
rand = "0.4"
either = "1.4"
objekt = "0.1"
failure = "0.1"
openssl = { git = "https://github.com/bkchr/rust-openssl.git", branch = "picoquic_rs" }
openssl-sys = { git = "https://github.com/bkchr/rust-openssl.git", branch = "picoquic_rs" }
hex = "0.3"